{
    "schema": "nfc",
    "tablename": "password_policy",
    "comment": "Парольная политика",
    "cols": [
        {
            "name": "attempts_to_lock",
            "datatype": "numeric",
            "datatype_length": "17,0",
            "datatype_full": "numeric(17,0)",
            "required": false,
            "default_value": null,
            "comment": "Количество попыток до блокирования учетной записи",
            "fk_tablename": null,
            "column_id": 4
        },
        {
            "name": "caption",
            "datatype": "varchar",
            "datatype_length": "300",
            "datatype_full": "character varying(300)",
            "required": true,
            "default_value": null,
            "comment": "Наименование",
            "fk_tablename": null,
            "column_id": 3
        },
        {
            "name": "code",
            "datatype": "varchar",
            "datatype_length": "60",
            "datatype_full": "character varying(60)",
            "required": true,
            "default_value": null,
            "comment": "Код",
            "fk_tablename": null,
            "column_id": 2
        },
        {
            "name": "id",
            "datatype": "int8",
            "datatype_length": null,
            "datatype_full": "bigint",
            "required": true,
            "default_value": "nextval('nfc.s_main'::text::regclass)",
            "comment": "Код",
            "fk_tablename": null,
            "column_id": 1
        },
        {
            "name": "pwd_chk_block",
            "datatype": "varchar",
            "datatype_length": "4000",
            "datatype_full": "character varying(4000)",
            "required": false,
            "default_value": null,
            "comment": "Код для проверки корректности пароля ($1-подстановка для заданного пароля)",
            "fk_tablename": null,
            "column_id": 11
        },
        {
            "name": "pwd_chk_block_remark",
            "datatype": "varchar",
            "datatype_length": "4000",
            "datatype_full": "character varying(4000)",
            "required": false,
            "default_value": null,
            "comment": "Пояснение к блоку для проверки",
            "fk_tablename": null,
            "column_id": 12
        },
        {
            "name": "pwd_lifetime",
            "datatype": "numeric",
            "datatype_length": "22,5",
            "datatype_full": "numeric(22,5)",
            "required": false,
            "default_value": null,
            "comment": "Срок действия пароля (в днях)",
            "fk_tablename": null,
            "column_id": 6
        },
        {
            "name": "pwd_locktime",
            "datatype": "numeric",
            "datatype_length": "22,5",
            "datatype_full": "numeric(22,5)",
            "required": false,
            "default_value": null,
            "comment": "Срок блокировки (в днях)",
            "fk_tablename": null,
            "column_id": 5
        },
        {
            "name": "pwd_minlength",
            "datatype": "numeric",
            "datatype_length": "2,0",
            "datatype_full": "numeric(2,0)",
            "required": false,
            "default_value": null,
            "comment": "Минимальная длина пароля",
            "fk_tablename": null,
            "column_id": 7
        },
        {
            "name": "pwd_use_digit",
            "datatype": "bool",
            "datatype_length": null,
            "datatype_full": "boolean",
            "required": false,
            "default_value": null,
            "comment": "Пароль должен содержать цифры",
            "fk_tablename": null,
            "column_id": 9
        },
        {
            "name": "pwd_use_shift",
            "datatype": "bool",
            "datatype_length": null,
            "datatype_full": "boolean",
            "required": false,
            "default_value": null,
            "comment": "Пароль должен содержать разные регистры сиволов",
            "fk_tablename": null,
            "column_id": 10
        },
        {
            "name": "pwd_use_specs",
            "datatype": "bool",
            "datatype_length": null,
            "datatype_full": "boolean",
            "required": false,
            "default_value": null,
            "comment": "Пароль должен содержать спецсимволы",
            "fk_tablename": null,
            "column_id": 8
        }
    ],
    "cons": [
        {
            "name": "ch4password_policy8caption",
            "schema": "nfc",
            "type": "c",
            "update_rule": null,
            "delete_rule": null,
            "condition": "((caption)::text = btrim((caption)::text))",
            "definition": "CHECK (caption::text = btrim(caption::text))",
            "r_schema": null,
            "r_tablename": null,
            "r_columnname": null,
            "columns": "caption",
            "comment": null,
            "deferrable": null
        },
        {
            "name": "ch4password_policy8code",
            "schema": "nfc",
            "type": "c",
            "update_rule": null,
            "delete_rule": null,
            "condition": "((code)::text = btrim((code)::text))",
            "definition": "CHECK (code::text = btrim(code::text))",
            "r_schema": null,
            "r_tablename": null,
            "r_columnname": null,
            "columns": "code",
            "comment": null,
            "deferrable": null
        },
        {
            "name": "pk4password_policy",
            "schema": "nfc",
            "type": "p",
            "update_rule": null,
            "delete_rule": null,
            "condition": null,
            "definition": "PRIMARY KEY (id)",
            "r_schema": null,
            "r_tablename": null,
            "r_columnname": null,
            "columns": "id",
            "comment": null,
            "deferrable": null
        },
        {
            "name": "uk4password_policy8caption",
            "schema": "nfc",
            "type": "u",
            "update_rule": null,
            "delete_rule": null,
            "condition": null,
            "definition": "UNIQUE (caption)",
            "r_schema": null,
            "r_tablename": null,
            "r_columnname": null,
            "columns": "caption",
            "comment": null,
            "deferrable": null
        },
        {
            "name": "uk4password_policy8code",
            "schema": "nfc",
            "type": "u",
            "update_rule": null,
            "delete_rule": null,
            "condition": null,
            "definition": "UNIQUE (code)",
            "r_schema": null,
            "r_tablename": null,
            "r_columnname": null,
            "columns": "code",
            "comment": null,
            "deferrable": null
        }
    ],
    "indx": null
}